### ISSUE TITLE
PV backup fails because it magically uses a random AZURE_CLIENT_ID

### ISSUE THREAD

**Issue by sami-alajrami** [vmware-tanzu/velero-plugin-for-microsoft-azure#57]
I am trying to make Persistent Volumes backups from AKS work (cluster state backup works fine).
My volumeSnapshotLocation looks like:

```yaml
Name:         default
Namespace:    velero
Labels:       app.kubernetes.io/instance=velero
              app.kubernetes.io/managed-by=Helm
              app.kubernetes.io/name=velero
              helm.sh/chart=velero-2.9.15
Annotations:  meta.helm.sh/release-name: velero
              meta.helm.sh/release-namespace: velero
API Version:  velero.io/v1
Kind:         VolumeSnapshotLocation
Metadata:
  Creation Timestamp:  2020-07-07T11:33:56Z
  Generation:          1
  Resource Version:    19224286
  Self Link:           /apis/velero.io/v1/namespaces/velero/volumesnapshotlocations/default
  UID:                 53d5880f-8813-4613-a761-28faa0e62636
Spec:
  Config:
    API Timeout:     10m
    Resource Group:  aks-generated_rg-excited-calf
  Provider:          azure
Events:              <none>

```
My backup object looks like:

```yaml
Name:         test-backup
Namespace:    velero
Labels:       app.kubernetes.io/instance=velero
              app.kubernetes.io/managed-by=Helm
              app.kubernetes.io/name=velero
              helm.sh/chart=velero-2.9.15
              velero.io/schedule-name=velero-daily-backup
              velero.io/storage-location=default
Annotations:  <none>
API Version:  velero.io/v1
Kind:         Backup
Metadata:
  Creation Timestamp:  2020-07-08T07:54:49Z
  Generation:          3
  Resource Version:    19469370
  Self Link:           /apis/velero.io/v1/namespaces/velero/backups/test-backup
  UID:                 8443da51-fecb-44f8-91ce-7f5b56f29749
Spec:
  Excluded Namespaces:
    kube-system
    velero
  Hooks:
  Snapshot Volumes:  true
  Storage Location:  default
  Ttl:               120h0m0s
  Volume Snapshot Locations:
    default
Status:
  Completion Timestamp:  2020-07-08T07:55:13Z
  Errors:                4
  Expiration:            2020-07-13T07:54:49Z
  Phase:                 PartiallyFailed
  Start Timestamp:       2020-07-08T07:54:49Z
  Version:               1
Events:                  <none>
```

 but it fails with the following error:
```
velero backup logs test-backup | grep -i error
time="2020-07-08T07:55:06Z" level=info msg="1 errors encountered backup up item" backup=velero/test-backup group=v1 logSource="pkg/backup/resource_backupper.go:283" name=prometheus-prometheus-operator-poc-prometheus-0 namespace= resource=pods
time="2020-07-08T07:55:06Z" level=error msg="Error backing up item" backup=velero/test-backup error="error getting volume info: rpc error: code = Unknown desc = compute.DisksClient#Get: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code=\"AuthorizationFailed\" Message=\"The client '5f96af7c-feb0-4f4b-a122-1b674d627839' with object id '5f96af7c-feb0-4f4b-a122-1b674d627839' does not have authorization to perform action 'Microsoft.Compute/disks/read' over scope '/subscriptions/XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX/resourceGroups/aks-generated_rg-excited-calf/providers/Microsoft.Compute/disks/kubernetes-dynamic-pvc-c238b1a0-cb1b-4d09-826d-bf607007f85f' or the scope is invalid. If access was recently granted, please refresh your credentials.\"" group=v1 logSource="pkg/backup/resource_backupper.go:287" name=prometheus-prometheus-operator-poc-prometheus-0 namespace= resource=pods
```
The error message is self explanatory. **But the weird thing is that the client ID `5f96af7c-feb0-4f4b-a122-1b674d627839` is not what I provide in /credentials/cloud.** I have no idea where velero/azure-sdk-for-go gets it from.

Here is a peek on my /credentials/cloud from within the velero pod:
```shell
nobody@velero-67875749d5-khqtx:/$ cat /credentials/cloud 
AZURE_SUBSCRIPTION_ID=XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX
AZURE_TENANT_ID=XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX
AZURE_CLIENT_ID=eed1ba5f-4f1b-41db-8b1c-5cd589c146cd # different from what velero tries to use
AZURE_CLIENT_SECRET=*******
AZURE_CLOUD_NAME=AzurePublicCloud
AZURE_RESOURCE_GROUP=aks-generated_rg-excited-calf
```
And when checking azure for the random client ID velero uses, it does not exist:
```shell
az ad sp show --id 5f96af7c-feb0-4f4b-a122-1b674d627839
Resource '5f96af7c-feb0-4f4b-a122-1b674d627839' does not exist or one of its queried reference-property objects are not present.
```
How can I make velero respect the client ID I am providing??

velero-plugin-for-microsoft-azure version: v1.0.0
