### ISSUE TITLE
Unable to use AAD Pod Identity

### ISSUE THREAD

**Issue by cfreemoser** [vmware-tanzu/velero-plugin-for-microsoft-azure#61]
Hey, I tried to get velero running with AAD Pod Identity. Sadly, the pod is always crashing. From the logs I would guess that velero has problems to authenticate

```
time="2020-08-10T07:26:45Z" level=info msg="Checking that all backup storage locations are valid" logSource="pkg/cmd/server/server.go:437"
An error occurred: some backup storage locations are invalid: error getting backup store for location "default": rpc error: code = Unknown desc = unable to get all required environment variables: the following keys do not have values: AZURE_TENANT_ID, AZURE_CLIENT_SECRET
```

I followed the introduction in the README and assigned all needed permissions (Contributor on related ResourceGroups). Following AzureIdentity and AzureIdentityBinding are deployed to the cluster:

```yaml
Name:         uai-velero-support
Namespace:    pos-backup
Labels:       <none>
Annotations:  API Version:  aadpodidentity.k8s.io/v1
Kind:         AzureIdentity
Metadata:
  Creation Timestamp:  2020-08-07T12:40:20Z
  Generation:          1
  Managed Fields:
    API Version:  aadpodidentity.k8s.io/v1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .:
          f:kubectl.kubernetes.io/last-applied-configuration:
      f:spec:
        .:
        f:clientID:
        f:resourceID:
        f:type:
    Manager:         kubectl
    Operation:       Update
    Time:            2020-08-07T12:40:20Z
  Resource Version:  31432
  Self Link:         /apis/aadpodidentity.k8s.io/v1/namespaces/pos-backup/azureidentities/uai-velero-support
  UID:               458f3cae-cb5a-4992-94e7-a598d1e490f7
Spec:
  Client ID:    xxx
  Resource ID:  xxx
  Type:         0
Events:         <none>
```

```yaml
Name:         uai-velero-support-binding
Namespace:    pos-backup
Labels:       <none>
Annotations:  API Version:  aadpodidentity.k8s.io/v1
Kind:         AzureIdentityBinding
Metadata:
  Creation Timestamp:  2020-08-07T12:40:31Z
  Generation:          1
  Managed Fields:
    API Version:  aadpodidentity.k8s.io/v1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .:
          f:kubectl.kubernetes.io/last-applied-configuration:
      f:spec:
        .:
        f:azureIdentity:
        f:selector:
    Manager:         kubectl
    Operation:       Update
    Time:            2020-08-07T12:40:31Z
  Resource Version:  31461
  Self Link:         /apis/aadpodidentity.k8s.io/v1/namespaces/pos-backup/azureidentitybindings/uai-velero-support-binding
  UID:               78067029-eb51-4177-ac7b-31aa2ff47f39
Spec:
  Azure Identity:  uai-velero-support
  Selector:        uai-velero-support
Events:            <none>
```

The secret also looks fine:

```yaml
AZURE_SUBSCRIPTION_ID=xxx
AZURE_RESOURCE_GROUP=MC_xxx_westeurope
AZURE_CLOUD_NAME=AzurePublicCloud`
```

I tested the AzureIdentity with the demo pod provided from Microsoft - therefore I am confident that the AAD Integration and the Identity, in general, are working.

Did I miss something?
