### ISSUE TITLE
Velero MSI install error using aad-pod-identity

### ISSUE THREAD

**Issue by AkhilaDamera** [vmware-tanzu/velero-plugin-for-microsoft-azure#62]
Error:
`
An error occurred: some backup storage locations are invalid: error getting backup store for location "default": rpc error: code = Unknown desc =  azure.BearerAuthorizer#WithAuthorization: Failed to refresh the Token for request to https://management.azure.com/subscriptions/id/resourceGroups/rg/providers/Microsoft.Storage/storageAccounts/st/listKeys?%24expand=kerb&api-version=2019-06-01: StatusCode=404 -- Original Error: adal: Refresh request failed. Status Code = '404'.  Response body: getting assigned identities for pod velero in CREATED state failed after 16 attempts, retry duration [5]s. Error: <nil>
`
I have tried role identity creation with aks resource group and also cluster node resource group but the error seems same 

Deploying using the below Helm chart:

`
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: velero
  namespace: backup
  labels:
    aadpodidbinding:  $Pod-Identity
spec:
  values:
    podAnnotations:
      backup.velero.io/backup-volumes: file

    configuration:
      provider: 'azure'
      backupStorageLocation:
        name: 'azure'
        bucket: 'bucket'
        config:
          resourceGroup: 'rg'
          storageAccount: 'st'
         
      volumeSnapshotLocation:
        name: 'st
        config:
          region: 'eastus2'
          resourceGroup: 'rg'

    initContainers:
      - name: velero-plugin-for-microsoft-azure
        image: velero/velero-plugin-for-microsoft-azure:main
        imagePullPolicy: IfNotPresent
        env: 
          - name: AZURE_CREDENTIALS_FILE
            value: /credentials/cloud
        volumeMounts:
          - mountPath: /target
            name: plugins
          - name: cloud-credentials
            mountPath: /credentials
    volumes:
      - name: cloud-credentials
        secret: 
          - secretName: cloud-credentials

    credentials:
      useSecret: true
      existingSecret: cloud-credentials
`

```
Created roles using below: 

cat <<EOF | kubectl apply -f -
apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzureIdentity
metadata:
  name: identity
  namespace: backup
spec:
  type: 0
  resourceID: /subscriptions/id/resourcegroups/MC_rg/providers/Microsoft.ManagedIdentity/userAssignedIdentities/rg
  clientID: 
EOF

cat <<EOF | kubectl apply -f -
apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzureIdentityBinding
metadata:
  name:identity-binding
  namespace: backup
spec:
  azureIdentity: identity
  selector: identity
EOF
```
