### ISSUE TITLE
Azure volumes snapshot issue

### ISSUE THREAD

**Issue by 5obol** [vmware-tanzu/velero-plugin-for-microsoft-azure#68]
Hi guys,
I am struggling with PVs backup on Azure with the usage of `velero-plugin-for-microsoft-azure`.
It backs up and sends into Azure Storage account everything except Volumes.
Softwares versions:
AKS:
```
infrastructure (mth/velero) $ kubectl version
Client Version: version.Info{Major:“1”, Minor:“16", GitVersion:“v1.16.2”, GitCommit:“c97fe5036ef3df2967d086711e6c0c405941e14b”, GitTreeState:“clean”, BuildDate:“2019-10-15T23:42:50Z”, GoVersion:“go1.12.10”, Compiler:“gc”, Platform:“darwin/amd64”}
Server Version: version.Info{Major:“1", Minor:“17”, GitVersion:“v1.17.7", GitCommit:“5737fe2e0b8e92698351a853b0d07f9c39b96736”, GitTreeState:“clean”, BuildDate:“2020-06-24T19:54:11Z”, GoVersion:“go1.13.6", Compiler:“gc”, Platform:“linux/amd64"}
```
Velero:
```
infrastructure (mth/velero) $ velero version
Client:
	Version: v1.5.0
	Git commit: -
Server:
	Version: v1.4.2
```
We do use `Managed Disks` on Azure (which is supposed to be suported disk type by Velero):
```
infrastructure (mth/velero) $ kubectl describe pv pvc-c8fdc5c9-4123-4323-9e17-c89de5e8436b | grep -i type
    Type:         AzureDisk (an Azure Data Disk mount on the host and bind mount to the pod)
```
Here is Veleros detailed describtion of backup created:
```
infrastructure (mth/velero) $ velero describe backup nginx-example-backup --details
Name:         nginx-example-backup
Namespace:    velero
Labels:       velero.io/storage-location=default
Annotations:  velero.io/source-cluster-k8s-gitversion=v1.17.7
              velero.io/source-cluster-k8s-major-version=1
              velero.io/source-cluster-k8s-minor-version=17
Phase:  Completed
Errors:    0
Warnings:  0
Namespaces:
  Included:  *
  Excluded:  <none>
Resources:
  Included:        *
  Excluded:        <none>
  Cluster-scoped:  auto
Label selector:  app=nginx
Storage Location:  default
Velero-Native Snapshot PVs:  true
TTL:  720h0m0s
Hooks:  <none>
Backup Format Version:  1
Started:    2020-09-08 17:42:38 +0300 EEST
Completed:  2020-09-08 17:42:43 +0300 EEST
Expiration:  2020-10-08 17:42:38 +0300 EEST
Total items to be backed up:  7
Items backed up:              7
Resource List:
  apps/v1/ReplicaSet:
    - nginx-example/nginx-deployment-f96b7fd86
  v1/Endpoints:
    - nginx-example/my-nginx
  v1/Namespace:
    - nginx-example
  v1/PersistentVolume:
    - pvc-c8fdc5c9-4123-4323-9e17-c89de5e8436b
  v1/PersistentVolumeClaim:
    - nginx-example/nginx-logs
  v1/Pod:
    - nginx-example/nginx-deployment-f96b7fd86-m5kws
  v1/Service:
    - nginx-example/my-nginx
Velero-Native Snapshots: <none included>
```
I have created it with the command as follow:
```
velero backup create nginx-example-backup --selector app=nginx --snapshot-volumes=true
```
Here is Helm chart’s configuration:
```
  - name: velero
    chart: {{ env “AZ_HELM_REPO” | default “containerregistrydsp” }}/velero
    version: 2.12.15
    namespace: velero
    installed: true
    values:
      - snapshotsEnabled: false
      - credentials:
          secretContents:
            cloud: |
              AZURE_STORAGE_ACCOUNT_ACCESS_KEY={{ requiredEnv “backups_sa_key” }}
              AZURE_CLOUD_NAME=AzurePublicCloud
          extraEnvVars: {}
      - configuration:
          provider: azure
          backupStorageLocation:
            name: default
            bucket: {{ requiredEnv “backups_sa_container” }}
            prefix: k8s_
            config:
              resourceGroup: {{ requiredEnv “backups_sa_rg” }}
              storageAccount: {{ requiredEnv “backups_sa_name” }}
              storageAccountKeyEnvVar: AZURE_STORAGE_ACCOUNT_ACCESS_KEY
              subscriptionId: {{ requiredEnv “subscription_id” }}
      - initContainers:
        - name: velero-plugin-for-azure
          image: velero/velero-plugin-for-microsoft-azure:v1.1.0
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - mountPath: /target
              name: plugins
```
And here is `Default` storage withing AKS:
```
infrastructure (mth/velero) $ kubectl get storageclasses.storage.k8s.io default -o yaml
allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {“allowVolumeExpansion”:true,“apiVersion”:“storage.k8s.io/v1beta1”,“kind”:“StorageClass”,“metadata”:{“annotations”:{“storageclass.beta.kubernetes.io/is-default-class”:“true”},“labels”:{“kubernetes.io/cluster-service”:“true”},“name”:“default”},“parameters”:{“cachingmode”:“ReadOnly”,“kind”:“Managed”,“storageaccounttype”:“StandardSSD_LRS”},“provisioner”:“kubernetes.io/azure-disk”}
    storageclass.beta.kubernetes.io/is-default-class: “true”
  creationTimestamp: “2020-09-04T15:14:13Z”
  labels:
    kubernetes.io/cluster-service: “true”
  name: default
  resourceVersion: “4836024"
  selfLink: /apis/storage.k8s.io/v1/storageclasses/default
parameters:
  cachingmode: ReadOnly
  kind: Managed
  storageaccounttype: StandardSSD_LRS
provisioner: kubernetes.io/azure-disk
reclaimPolicy: Delete
volumeBindingMode: Immediate
```
And here what I see in the logs all the time:
```
time=“2020-09-08T13:58:00Z” level=info msg=“Backing up item” backup=velero/nginx-example-backup logSource=“pkg/backup/item_backupper.go:120” name=nginx-logs namespace=nginx-example resource=persistentvolumeclaims
time=“2020-09-08T13:58:00Z” level=info msg=“Executing custom action” backup=velero/nginx-example-backup logSource=“pkg/backup/item_backupper.go:326" name=nginx-logs namespace=nginx-example resource=persistentvolumeclaims
time=“2020-09-08T13:58:00Z” level=info msg=“Executing PVCAction” backup=velero/nginx-example-backup cmd=/velero logSource=“pkg/backup/backup_pv_action.go:49” pluginName=velero
time=“2020-09-08T13:58:00Z” level=info msg=“Backing up item” backup=velero/nginx-example-backup logSource=“pkg/backup/item_backupper.go:120" name=pvc-c8fdc5c9-4123-4323-9e17-c89de5e8436b namespace= resource=persistentvolumes
time=“2020-09-08T13:58:00Z” level=info msg=“Executing takePVSnapshot” backup=velero/nginx-example-backup logSource=“pkg/backup/item_backupper.go:404” name=pvc-c8fdc5c9-4123-4323-9e17-c89de5e8436b namespace= resource=persistentvolumes
time=“2020-09-08T13:58:00Z” level=info msg=“Persistent volume is not a supported volume type for snapshots, skipping.” backup=velero/nginx-example-backup logSource=“pkg/backup/item_backupper.go:468" name=pvc-c8fdc5c9-4123-4323-9e17-c89de5e8436b namespace= persistentVolume=pvc-c8fdc5c9-4123-4323-9e17-c89de5e8436b resource=persistentvolumes
...
```
It was also complaining about some labels (zone description) are missing on PV’s declaration.
I have added them into PV and now those errors/issues are gone:
```
infrastructure (mth/velero) $ kubectl get persistentvolumeclaims -n nginx-example nginx-logs -o yaml | grep -i zone
    topology.kubernetes.io/zone: “0”
```
Hence playing here or there only returns always:
- either `Persistent volume is not a supported volume type for snapshots, skipping.`
- or `topology.kubernetes.io/zone label is not found in PVs ....`
Please assist as I have no idea what else can be done or checked. And why it says that `Persistent volume is not supported type of snapshots`. Even though in accordance with this: https://velero.io/docs/v1.3.2/supported-providers/ we do use needed plugin and supported type of Volumnes.
